# Generated by Django 4.1.2 on 2022-10-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='resource',
            new_name='album',
        ),
    ]
